//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.10 at 02:00:29 PM CEST 
//


package com.adrianpratik.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cardsPositionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cardsPositionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="player" type="{}playerType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="deck" type="{}deckType"/>
 *         &lt;element name="discardDeck" type="{}discardDeckType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cardsPositionType", propOrder = {
    "player",
    "deck",
    "discardDeck"
})
public class CardsPositionType {

    protected List<PlayerType> player;
    @XmlElement(required = true)
    protected DeckType deck;
    @XmlElement(required = true)
    protected DiscardDeckType discardDeck;

    /**
     * Gets the value of the player property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the player property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlayer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlayerType }
     * 
     * 
     */
    public List<PlayerType> getPlayer() {
        if (player == null) {
            player = new ArrayList<PlayerType>();
        }
        return this.player;
    }

    /**
     * Gets the value of the deck property.
     * 
     * @return
     *     possible object is
     *     {@link DeckType }
     *     
     */
    public DeckType getDeck() {
        return deck;
    }

    /**
     * Sets the value of the deck property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeckType }
     *     
     */
    public void setDeck(DeckType value) {
        this.deck = value;
    }

    /**
     * Gets the value of the discardDeck property.
     * 
     * @return
     *     possible object is
     *     {@link DiscardDeckType }
     *     
     */
    public DiscardDeckType getDiscardDeck() {
        return discardDeck;
    }

    /**
     * Sets the value of the discardDeck property.
     * 
     * @param value
     *     allowed object is
     *     {@link DiscardDeckType }
     *     
     */
    public void setDiscardDeck(DiscardDeckType value) {
        this.discardDeck = value;
    }

}
